### ISSUE TITLE
Max Poly-X

### ISSUE THREAD

**Issue by JFresnedo** [aresti/primalscheme#25]
Hello, thanks for the great work with primalscheme. A quick question: I am designing amplicons for which I need to set PRIMER_MAX_POLY_X = 3. Is it enough adding this parameter to config.py or do I need to modify another file as well?

**Comment by aresti** [comment]
Hi! We don't match the primer3 setting name here sorry, its PRIMER_MAX_HOMO in config.py. Make sure to use the editable install method
