### ISSUE TITLE
suggestion to hair pin temperature

### ISSUE THREAD

**Issue by isabelluo** [aresti/primalscheme#31]
What is the acceptable Hairpin Tm for the multiplex system? 
Does the program take hairpin Tm under consideration when designing primers?

**Comment by aresti** [comment]
Hi,

Yes, hairpin Tm is considered (we use primer3 for this). You can see all the default thresholds in [config.py](https://github.com/aresti/primalscheme/blob/master/src/primalscheme/config.py).

**Comment by isabelluo** [comment]
Hi 
But I input the primer designed into geneious prime and the Hair pin Tm showed to be 48.7C in some primers. Is this expected? I heard that it is suggetsed that the Hair pin Tm should be 50 C lower than the annealing temperature though....

**Comment by joshquick** [comment]
As @aresti said all the thermodynamic parameters used are in the config.py. I've copied the lines relevant to hairpin prediction below so if you want adjust them you can.

PRIMER_MAX_HAIRPIN_TH = 47.0
MV_CONC = 100.0
DV_CONC = 2.0
DNA_CONC = 15.0
DNTP_CONC = 0.8

**Comment by isabelluo** [comment]
Thank you @joshquick
